### DISCUSSION TITLE
Creation/Discussion on auto-labelling of PRs

### DISCUSSION THREAD

**Discussion by kushthedude** [meshery/meshery#969] [General] [answered]
Since releaseDrafter requires PR to be labelled accordingly so that they may be clubbed into a category, this issue serves as the starting of which labels and what categories should we have.

**Comment by kushthedude** [comment, marked as answer]
@leecalcote Let's save ourselves from the pain of maintaining a consistent PR naming or commit title. I looped upon something nice today which would do the most of work for us. We help of this little tool https://github.com/apps/probot-autolabeler, we can label PR according to changes involved concerning the directory
```yml

mesheryctl: ["/mesheryctl/"]
UI: ["ui", "/provider-ui"]
documentation: ["docs/", "readme.md", "changelog"]
```
and some more like the following after having a discussion .
