### ISSUE TITLE
[Server] Kubernetes Manifest Import Enhancement

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10072]
### Current Behavior
When importing a covenant is manifest, that includes multiple yeah, I'm all new file markers (`---`) in a row, the measure, if I was to import the manifest. Example:

```yaml
.
.
---
---
.
.
```

### Desired Behavior
1. Ignore redundant document boundary markers.

### Implementation
1. Ideally, Meshery uses the Kubernetes client go or similar library to parse through the manifest and ignore redundant YAML document boundary markers.

### Acceptance Tests
1. Users can successfully import long manifest files that have one or more (e.g. more than two) document boundary markers in a row.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Dhanush0369** [comment]
@leecalcote I have understood the issue. I know to use go package "gopkg.in/yaml.v3" for  parsing the manifest and ignore redundant YAML document boundary markers.
If kuberntes client-go library is preferable then I can complete the task using that as well. Please assign me.

**Comment by leecalcote** [comment]
Thanks for stepping up, @Dhanush0369 👍 @theBeginner86, please be aware of @Dhanush0369's impending activity here. // @MUzairS15

**Comment by theBeginner86** [comment]
@leecalcote 
There is likely some mis-understanding here.
Any user can very well import a manifest with multiple boundary markers `---` inside of it.

The issue you are facing is due to the use of manifests that has CRDs unrecognized by your Meshery Server, that is, missing registered components for Kustomize, ExternalSecret etc.
Secondly, there is are couple syntax error around line 892 that has misplacement of boundary marker.

![Screenshot 2024-01-25 at 8 00 53 PM](https://github.com/meshery/meshery/assets/73700530/35a12c44-0a6f-4b32-abbf-f3424f57f3b5)


// @Dhanush0369

**Comment by theBeginner86** [comment]
For testing you can use the following manifest that has multiple boundary marker (including redundant ones)

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376

```
