### ISSUE TITLE
[mesheryctl] `pattern import` results in Response Status Code 500, possibly Server error

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12094]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
**command**

```
$ mesheryctl pattern import -f percona.yaml -s manifest
Unable to create a response from requestResponse Status Code 500, possibly Server error
```

**manifest**

```
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMySQL
metadata:
  name: my-mysql-deployment
  namespace: my-mysql-namespace # Replace with your desired namespace
spec:
  version: 8.0 # Or your desired MySQL version
  secretsName: my-mysql-secrets # Replace with the name of your secrets
  volumeSpec:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 1Gi # Adjust the storage size as needed
```

### Desired Behavior
I should get an understandable explanation (using MeshKit error code) that explains what went wrong and what to do about it.

### Screenshots/Logs
```
$ mesheryctl pattern import -f percona.yaml -s manifest
Unable to create a response from requestResponse Status Code 500, possibly Server error
```

### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.7.105
- Meshery Client Version: stable-v0.7.105
- Platform: Locally built and running Meshery Server

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
