### ISSUE TITLE
[Models] Support `Kustomization`.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#12168]
### Current Situation

On importing manifests containing `Kustomization` resources, Meshery server is unable to handle it and errors out.
<details>

<summary>
Manifest.yml
</summary>

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - backup-job
  - obc.yaml
namespace: vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-job
---
# Used for inspecting PVC used for the job, or retrieving/restoring snapshots

# To retrieve a snapshot, deploy this pod in vault backup namespace
# Then set VAULT_ADDR, have the root token ready
# `oc rsh` into the toolbox container and run `vault login`
# Use the root token to login.
# Find the latest snapshot in the /snapshots directory. This is the pvc where snapshots are stored.
# Then run `vault operator raft snapshot restore -force snapshot-${LATEST_TIMESTAMP}.snap`
# You can also download the snapshot to your local file system by running:
# oc cp debug-pod:/snapshots/snapshot-${LATEST_TIMESTAMP}.snap snapshot-${LATEST_TIMESTAMP}.snap
# And restore vault via vault CLI from your local file system.
apiVersion: v1
kind: Pod
metadata:
  name: backup-toolkit
spec:
  serviceAccountName: backup-job
  containers:
    - name: toolbox
      image: quay.io/operate-first/opf-toolbox:v0.8.0
      command:
        - sleep
        - "36000"
      volumeMounts:
        - mountPath: /snapshots
          name: snapshots
        - mountPath: /backup-job
          name: backup-job
    - name: mc
      image: quay.io/operate-first/mc:RELEASE.2022-06-17T02-52-50Z
      command:
        - sleep
        - "36000"
      volumeMounts:
        - mountPath: /snapshots
          name: snapshots
        - mountPath: /backup-job
          name: backup-job
  volumes:
    - name: snapshots
      persistentVolumeClaim:
        claimName: vault-snapshots
    - name: backup-job
      secret:
        secretName: backup-job
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
namespace: vault
configMapGenerator:
  - files:
      - taskrun.yaml
    name: backup-vault-run
  - files:
      - scripts/backup-snapshot-to-s3.sh
      - scripts/cleanup-old-taskruns.sh
      - scripts/create-snapshot.sh
      - scripts/prune-old-snapshots.sh
    name: utility-scripts
resources:
  - cronjob.yaml
  - pvc.yaml
  - rolebinding.yaml
  - sa.yaml
  - task.yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: backup-vault
spec:
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  workspaces:
    - name: snapshots
      mountPath: /snapshots
    - name: backup-job
      mountPath: /backup-job
    - name: utility-scripts
      mountPath: /utility-scripts
  steps:
    # This step creates a snapshot of the vault instance and
    # backs it up to a pvc. Subsequent steps use mc client
    # to mirror contents of this PVC to buckets, as well us
    # pruning data/resources
    - name: create-snapshot
      image: quay.io/operate-first/opf-toolbox:v0.8.0
      workingDir: /workspace
      command:
        - '/utility-scripts/create-snapshot.sh'
        - $(workspaces.snapshots.path)
        - $(context.taskRun.namespace)
    # This step cleans the pvc from the previous step of
    # any old data.
    - name: prune-old-snapshots
      image: quay.io/operate-first/mc:RELEASE.2022-06-17T02-52-50Z
      workingDir: /workspace
      command:
        - '/utility-scripts/prune-old-snapshots.sh'
        - $(workspaces.snapshots.path)
    # Clean old jobs, # of jobs to keep is configured in backup config
    # secret.
    - name: cleanup-old-taskruns
      image: quay.io/operate-first/opf-toolbox:v0.8.0
      workingDir: /workspace
      command:
        - '/utility-scripts/cleanup-old-taskruns.sh'

    # Backup data to target s3. Bucket is configured in backup config.
    # Add a similar step for another bucket to back up data to.
    # Update the 3rd argument to match the prefix in the secret.
    - name: backup-snapshot-to-s3-smaug
      image: quay.io/operate-first/mc:RELEASE.2022-06-17T02-52-50Z
      workingDir: /workspace
      command:
        - '/utility-scripts/backup-snapshot-to-s3.sh'
        - $(workspaces.snapshots.path)
        - smaug
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-backup-job
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 1,13 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: trigger-backup-job
        spec:
          serviceAccountName: backup-job
          volumes:
            - name: backup-vault-run
              configMap:
                name: backup-vault-run
          containers:
            - name: submit-backup-job
              image: quay.io/operate-first/opf-toolbox:v0.8.0
              env:
                - name: POD_NS
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              command:
                - "/bin/sh"
                - "-ec"
                - "oc create -f /backupjob/taskrun.yaml -n ${POD_NS}"
              volumeMounts:
                - mountPath: /backupjob
                  name: backup-vault-run
          restartPolicy: Never
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-snapshots
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
#!/bin/sh
set -e
NUM_TO_KEEP=$(cat /backup-job/OldJobsToKeepCount)
while read -r TASK; do
  while read -r TASK_TO_REMOVE; do
    test -n "${TASK_TO_REMOVE}" || continue;
    oc delete ${TASK_TO_REMOVE} \
        && echo "$(date -Is) TaskRun ${TASK_TO_REMOVE} deleted." \
        || echo "$(date -Is) Unable to delete TaskRun ${TASK_TO_REMOVE}.";
  done < <(oc get taskrun -l tekton.dev/task=${TASK} --sort-by=.metadata.creationTimestamp -o name | head -n -${NUM_TO_KEEP});
done < <(oc get taskrun -o go-template='{{range .items}}{{index .metadata.labels "tekton.dev/task"}}{{"\n"}}{{end}}' | uniq);
---
#!/bin/sh
set -e

snapshot_pvc_path=$1
bucket=$2
s3EndPoint=$(cat /backup-job/${bucket}-s3EndPoint)
s3AccessKey=$(cat /backup-job/${bucket}-s3AccessKey)
s3SecretKey=$(cat /backup-job/${bucket}-s3SecretKey)
s3Bucket=$(cat /backup-job/${bucket}-s3BucketName)
s3Retention=$(cat /backup-job/${bucket}-s3Retention)

echo "Setting up mc connection to s3 Bucket"
mc alias set store ${s3EndPoint} ${s3AccessKey} ${s3SecretKey} --api S3v4

echo "Syncing contents of ${snapshot_pvc_path}/ to Bucket ${s3Bucket} that are newer than ${s3Retention}"
mc mirror ${snapshot_pvc_path}/ store/${s3Bucket}/ --newer-than ${s3Retention}

echo "Removing files from Bucket ${s3Bucket} that are older than ${s3Retention}"
mc rm -r --force --older-than ${s3Retention} store/${s3Bucket}
echo "Done."

echo "Printing contents of Bucket ${s3Bucket}"
echo "--------------------------------------------"
mc ls store/${s3Bucket}
echo "--------------------------------------------"
echo "Done!"
---
#!/bin/sh
set -e

PVCRetention=$(cat /backup-job/PVCRetention)
snapshot_pvc_path=$1

echo "Removing files from PVC that are older than ${PVCRetention} in path ${snapshot_pvc_path}"
mc rm -r --force --older-than ${PVCRetention} ${snapshot_pvc_path}/
echo "Done."

echo "Printing contents of PVC"
echo "--------------------------------------------"
ls ${snapshot_pvc_path} -lha
echo "--------------------------------------------"
echo "Done!"
---
#!/bin/sh
set -e

snapshot_pvc_path=$1
taskrun_namespace=$2

echo "Logging into opf-vault-0 to retrieve leader"

oc exec -i opf-vault-0 -- vault operator raft list-peers --format=json > /tmp/peers.json
leader=$(yq e '.data.config.servers.[] | select(.leader == "true") | .address' -P /tmp/peers.json | cut -d '.' -f1)

echo "retrieved leader: ${leader}"
echo "Creating Snapshot in leader pod ${leader}..."

export snapshot_file_path=$(echo snapshot-"`date +"%F_T%H-%M-%S"`".snap)
oc exec -i $leader -- vault operator raft snapshot save /tmp/backup_job_snapshot.snap

echo "Snapshot created in Vault Leader pod. Moving snapshot from pod to backup PVC."


oc cp ${taskrun_namespace}/$leader:/tmp/backup_job_snapshot.snap ${snapshot_pvc_path}/${snapshot_file_path}
oc exec -i $leader -- rm /tmp/backup_job_snapshot.snap

echo "Backup Snapshot saved at ${snapshot_pvc_path}/$snapshot_file_path"
echo "Listing current snapshots in backedup PVC"

echo "--------------------------------------------"
ls -lha ${snapshot_pvc_path}
echo "--------------------------------------------"

echo "Done!"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backup-job
subjects:
  - kind: ServiceAccount
    name: backup-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
# This file should be deployed and managed manually with root creds to s3
# As this is tied to the vault back up job, having this secret managed
# by vault introduces a circular dependency.
apiVersion: v1
kind: Secret
metadata:
  name: backup-job
stringData:
  # Smaug s3 store
  smaug-s3AccessKey: ""  # Add manually
  smaug-s3SecretKey: ""  # Add manually
  smaug-s3BucketName: "opf-vault-snapshots"
  smaug-s3EndPoint: "https://s3-openshift-storage.apps.smaug.na.operate-first.cloud"
  smaug-s3Retention: "1d"

  # Add another s3 store template, replace <bucket-prefix>
  # with a unique value different from the prefixes above
  # this prefix will be passed as an argument to the
  # backup step in the tekton task.

  # <bucket-prefix>-s3AccessKey: ""
  # <bucket-prefix>-s3SecretKey: ""
  # <bucket-prefix>-s3BucketName: ""
  # <bucket-prefix>-s3EndPoint: ""
  # <bucket-prefix>-s3Retention: "1d"

  PVCRetention: "2d"
  OldJobsToKeepCount: "10"
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: backup-vault-run
spec:
  serviceAccountName: backup-job
  taskRef:
    name: backup-vault
  workspaces:
    - name: snapshots
      persistentVolumeClaim:
        claimName: vault-snapshots
    - name: backup-job
      secret:
        secretName: backup-job
    - name: utility-scripts
      configMap:
        name: utility-scripts
        defaultMode: 110
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: opf-vault-snapshots
spec:
  bucketName: opf-vault-snapshots
  objectBucketName: obc-vault-opf-vault-snapshots
  storageClassName: openshift-storage.noobaa.io
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
---
apiVersion: v1
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true

    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }

    storage "raft" {
      path = "/vault/data"
    }

    service_registration "kubernetes" {}

kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: opf-vault-config
  namespace: vault
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - route.yaml
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vault-ui
  namespace: vault
spec:
  to:
    kind: Service
    name: opf-vault
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: http
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
  name: opf-vault
  namespace: vault
spec:
  serviceName: opf-vault-internal
  podManagementPolicy: Parallel
  replicas: 3
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      app.kubernetes.io/instance: opf
      component: server
  template:
    metadata:
      labels:
        helm.sh/chart: vault-0.19.0
        app.kubernetes.io/name: vault
        app.kubernetes.io/instance: opf
        component: server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vault
                  app.kubernetes.io/instance: "opf"
                  component: server
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      serviceAccountName: opf-vault
      volumes:
        - name: config
          configMap:
            name: opf-vault-config
        - name: home
          emptyDir: {}
      containers:
        - name: vault
          image: quay.io/operate-first/vault:1.9.2
          imagePullPolicy: IfNotPresent
          command:
          - "/bin/sh"
          - "-ec"
          args:
          - |
            cp /vault/config/extraconfig-from-values.hcl /tmp/storageconfig.hcl;
            [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /tmp/storageconfig.hcl;
            [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /tmp/storageconfig.hcl;
            [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /tmp/storageconfig.hcl;
            [ -n "${API_ADDR}" ] && sed -Ei "s|API_ADDR|${API_ADDR?}|g" /tmp/storageconfig.hcl;
            [ -n "${TRANSIT_ADDR}" ] && sed -Ei "s|TRANSIT_ADDR|${TRANSIT_ADDR?}|g" /tmp/storageconfig.hcl;
            [ -n "${RAFT_ADDR}" ] && sed -Ei "s|RAFT_ADDR|${RAFT_ADDR?}|g" /tmp/storageconfig.hcl;
            /usr/local/bin/docker-entrypoint.sh vault server -config=/tmp/storageconfig.hcl
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VAULT_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_API_ADDR
              value: "http://$(POD_IP):8200"
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_CLUSTER_ADDR
              value: "https://$(HOSTNAME).opf-vault-internal:8201"
            - name: HOME
              value: "/home/vault"
          volumeMounts:
            - name: data
              mountPath: /vault/data
            - name: config
              mountPath: /vault/config
            - name: home
              mountPath: /home/vault
          ports:
            - containerPort: 8200
              name: http
            - containerPort: 8201
              name: https-internal
            - containerPort: 8202
              name: http-rep
          readinessProbe:
            # Check status; unsealed vault servers return 0
            # The exit code reflects the seal status:
            #   0 - unsealed
            #   1 - error
            #   2 - sealed
            exec:
              command: ["/bin/sh", "-ec", "vault status -tls-skip-verify"]
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          lifecycle:
            # Vault container doesn't receive SIGTERM from Kubernetes
            # and after the grace period ends, Kube sends SIGKILL.  This
            # causes issues with graceful shutdowns such as deregistering itself
            # from Consul (zombie services).
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  # Adding a sleep here to give the pod eviction a
                  # chance to propagate, so requests will not be made
                  # to this pod while it's terminating
                  "sleep 5 && kill -SIGTERM $(pidof vault)",
                ]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmaps/
- policy/
- rbac.authorization.k8s.io/
- route
- serviceaccounts/
- services/
- statefulsets/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: opf-vault
  namespace: vault
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rolebindings/rolebinding.yaml
  - roles/role.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: opf-vault-discovery-rolebinding
  namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opf-vault-discovery-role
subjects:
  - kind: ServiceAccount
    name: opf-vault
    namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: opf-vault-discovery-role
  namespace: vault
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
      - update
      - patch
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-ui
    helm.sh/chart: vault-0.18.0
  name: opf-vault-ui
  namespace: vault
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/name: vault
    component: server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: opf-vault-active
  namespace: vault
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/name: vault
    component: server
    vault-active: "true"
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: opf-vault-internal
  namespace: vault
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/name: vault
    component: server
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - opf-vault/service.yaml
  - opf-vault-active/service.yaml
  - opf-vault-internal/service.yaml
  - opf-vault-standby/service.yaml
  - opf-vault-ui/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: opf-vault
  namespace: vault
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/name: vault
    component: server
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: opf-vault-standby
  namespace: vault
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/name: vault
    component: server
    vault-active: "false"
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - poddisruptionbudget.yaml
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/instance: opf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.18.0
  name: opf-vault
  namespace: vault
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: opf
      app.kubernetes.io/name: vault
      component: server
---

```
</details>

### Proposed Change

Support `Kustomization` as an intergration with Meshery.

---

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 📚 [Models](https://docs.meshery.io/concepts/logical/models)
  - 📚 [Components](https://docs.meshery.io/concepts/logical/components)
  - 📚 [Relationships](https://docs.meshery.io/concepts/logical/components)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

 ### Contributing to Meshery Models
 - [Contributing Models](https://docs.meshery.io/project/contributing/contributing-models)
   - [Contributing Components](https://docs.meshery.io/project/contributing/contributing-components)
   - [Contributing Relationships](https://docs.meshery.io/project/contributing/contributing-relationships)
