### ISSUE TITLE
[UI] Failed to import a Meshery Design as type Docker Compose

### ISSUE THREAD

**Issue by weilirs** [meshery/meshery#12495]
### Current Behavior

Failed to import a Meshery Design as type Docker Compose, the Docker Compose file I used is from the existing design.(More details below)
### Desired Behavior

I should be able to import this Docker Compose file.
### Screenshots/Logs

This is the place I imported the Docker Compose file
![image](https://github.com/user-attachments/assets/e370c5eb-4a4e-492e-b21e-e3e7d3e5d944)

The Docker Compose file I used(downloaded from the existing design)
```
version: "3.8"
services:
  anythink-backend:
    build: ./backend
    container_name: anythink-backend
    command: sh -c "cd backend && yarn install && /wait-for-it.sh mongodb:27017 -q -t 60 && yarn dev"

    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/backend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "mongodb"

  anythink-frontend:
    build: ./frontend
    container_name: anythink-frontend
    command: sh -c "cd frontend && yarn install && yarn start"
    environment:
      - NODE_ENV=development
      - PORT=3001
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/frontend/node_modules
    ports:
      - "3001:3001"

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    logging:
      driver: none
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - '27017:27017'
```
![image](https://github.com/user-attachments/assets/3745d57f-c38d-4fc7-bfa5-396c8ba6674e)

The error I got
![image](https://github.com/user-attachments/assets/e173ce29-5b8e-4b7b-a79a-bb82c191b51b)

so I modified the first line to `version: "1.0"`, the Docker Compose file becomes
```
version: "1.0"
services:
  anythink-backend:
    build: ./backend
    container_name: anythink-backend
    command: sh -c "cd backend && yarn install && /wait-for-it.sh mongodb:27017 -q -t 60 && yarn dev"

    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/backend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "mongodb"

  anythink-frontend:
    build: ./frontend
    container_name: anythink-frontend
    command: sh -c "cd frontend && yarn install && yarn start"
    environment:
      - NODE_ENV=development
      - PORT=3001
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/frontend/node_modules
    ports:
      - "3001:3001"

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    logging:
      driver: none
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - '27017:27017'
```

Now I got this error
![image](https://github.com/user-attachments/assets/977070aa-c738-4f49-a6cb-c21a8253d5e4)

### Environment

- Browser: Arc
- Host OS: Mac 
- Meshery Server Version: v0.7.128
- Platform: Docker

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
