### ISSUE TITLE
upgrade statichcheck-action to `v1.3.0` across all repos

### ISSUE THREAD

**Issue by devhindo** [meshery/meshery#13041]
dominikh/staticcheck-action@v1.2.0 should be upgraded across all repos wherever it's used to `v1.3.0` with these configurations:
```yml
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "latest"
          install-go: false
```
which is part of the static check workflow:
```yml
  static_check:
    name: Static check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "latest"
          install-go: false

```
