### ISSUE TITLE
Support Import of Multi-Pod Kubernetes Manifests (kind: List) 

### ISSUE THREAD

**Issue by souvikinator** [meshery/meshery#13231]
### Current Behavior
When attempting to import a YAML file containing multiple pod manifest (exported from `kubectl get pods -n <namespace> -o yaml`), Meshery Kanvas fails to process the manifest. 

In contrast, importing a single pod manifest works correctly. 

### Desired Behavior

Successfully parse and recognize Kubernetes manifests of `kind: List` and process individual manifests in the list. Example List manifest structure that should be supported:

```yml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: pod1
  spec:
    # Pod 1 specifications
- apiVersion: v1
  kind: Pod
  metadata:
    name: pod2
  spec:
    # Pod 2 specifications
```

### Acceptance Tests
Export multiple pods from a Kubernetes namespace:

```bash
kubectl get pods -n test-namespace -o yaml > multiple-pods.yaml
```
Import the resulting YAML file into Kanvas and verify:
- All pods from the manifest are successfully imported

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
