### ISSUE TITLE
[CI] Invalid relationship depth in rego formatter

### ISSUE THREAD

**Issue by marblom007** [meshery/meshery#14579]
### Current Behavior
See https://github.com/meshery/meshery/actions/runs/14754111691/job/41418103230?pr=14574

### Implementation
```
      - name: Commit formatted Rego files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "**/*.rego"  # Target only Rego files
          commit_user_name: "GitHub Actions"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_message: "chore: auto-format Rego files"
          commit_options: "--no-verify"  # Skip hooks if needed
          branch: ${{ github.ref_name }}  # Use ref_name instead of head_ref
```

### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)
