### ISSUE TITLE
adding created_at/added field inside the registry model metadata

### ISSUE THREAD

**Issue by FaheemOnHub** [meshery/meshery#15021]
### Current Behavior

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/2e9d842f-3b4d-4a16-aa1b-823e280ce785" />

### Desired Behavior
have a field such as created_at/added_at inside the model metadata , so in frontend we can implement recently added / new models indicator.

@zihanKuang 
@aabidsofi19 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://meshery.io/community#community-forums) and [Community Slack](https://slack.meshery.io)

**Comment by FaheemOnHub** [comment]
@zihanKuang Are u tracking this, if not assign someone else

**Comment by zihanKuang** [comment]
Hi @FaheemOnHub, thanks for checking in. 
I'm not familiar enough with the model codebase, and I'm not sure which files would be involved.🤔It might be better for someone who has worked on the models before.

**Comment by FaheemOnHub** [comment]
> Hi [@FaheemOnHub](https://github.com/FaheemOnHub), thanks for checking in. I'm not familiar enough with the model codebase, and I'm not sure which files would be involved.🤔It might be better for someone who has worked on the models before.

thanks for confirming , will put in slack to see if someone will take this

**Comment by lekaf974** [comment]
@FaheemOnHub Can you share the endpoint targeted please, I can take a look on this

On cli side looks data is returned by API
```
./mesheryctl model view cass-operator
id: 23a4193a-4046-5df6-a055-171e31df4b1b
schemaVersion: models.meshery.io/v1beta1
version: v1.0.0
name: cass-operator
displayName: Apache Cassandra
status: enabled
registrant:
  id: cf1d6acd-4509-e589-1c1e-3f20f8aaf715
  name: Artifact Hub
  type: registry
  sub_type: ""
  kind: artifacthub
  status: registered
  created_at: 2025-08-29T11:41:05.792668289Z
  updated_at: 2025-08-29T11:41:05.792668289Z
  schemaVersion: ""
connection_id: cf1d6acd-4509-e589-1c1e-3f20f8aaf715
category:
  id: 57ac9798-d7b7-f045-bfc0-b0d89924101f
  name: App Definition and Development
subCategory: Database
metadata:
  isAnnotation: false
  primaryColor: '#373535'
  secondaryColor: '#00D3A9'
  svgWhite: ui/public/static/img/meshmodels/cass-operator/white/cass-operator-white.svg
  svgColor: ui/public/static/img/meshmodels/cass-operator/color/cass-operator-color.svg
  svgComplete: ""
  shape: barrel
model:
  version: 0.60.0
components_count: 3
relationships_count: 0
components: null
relationships: null

```
