### ISSUE TITLE
[mesheryctl] Enhance `context view` to display context-specific token 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3401]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

This child issue is related to epic #3286 for new token command.

#### Current Behavior
Tokens are in process of being written into meshconfig (~/.meshery/config.yaml). See #3396.

#### Desired Behavior
Nearly all of the mesheryctl commands will need to account for and use the active context's token. `mesheryctl system context` is one of those. `mesheryctl system context view` should include all details the associated token.

#### Screenshots/Logs

Current implementation is missing token location.

```
➜  ~ mesheryctl system context view

Current Context: local

endpoint: http://localhost:9081
token: Default
platform: docker
adapters:
- meshery-istio
- meshery-linkerd
- meshery-consul
- meshery-nsm
- meshery-kuma
- meshery-cpx
- meshery-osm
- meshery-traefik-mesh
channel: stable
version: latest

➜  ~ cat ~/.meshery/config.yaml
contexts:
  local:
    endpoint: http://localhost:9081
    token: Default
    platform: docker
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-traefik-mesh
    channel: stable
    version: latest
current-context: local
tokens:
- location: auth.json
  name: Default
```

#### Acceptance Tests

- [ ] User sees token name and location of active context when executing `mesheryctl system context view`.
  - [ ] Unit test should cover this scenario.
- [ ] User sees token name and location of specified context when executing `mesheryctl system context view --context <name>`.
  - [ ] Unit test should cover this scenario.
- [ ] Presence of a token in the context should be verified. If token name is not specified or is missing from context, then the user should be shown the contents of the context with a warning that token could not be found. 
  - [ ] Unit test should cover this scenario.
- [ ] Full definition of token in meshconfig file should be verified. If token name is provided in the context, but a token of that same name is not available in the `tokens:` stanza, then the user should be shown the contents of the context with a warning that token could not be found. 
  - [ ] Unit test should cover this scenario.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)
