### ISSUE TITLE
[meshery-server] supporting auth protocols not supported by `k8s.io/client-go` natively

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#4184]
#### Description
`k8s.io/client-go` and other tools (kubectl) need to be authenticated first using the cloud provider's auth methods before they can interact with the cluster.
For doing this, they generally depend on external CLIs given by the providers. For more information on this, lookup [this](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins).

When the application using the k8s client library is installed in the cluster, it doesn't need this authentication. However, out-of-cluster applications need to authenticate first.
Thus, to work with an environment in which Meshery is deployed out of cluster and connected to a managed cluster like EKS, Meshery needs to support this authentication.

For EKS, this is handled by the `aws` cli. Particularly the `aws eks get-token` command.
a Kubeconfig for EKS looks like the one below implying every time any `kubectl` command is executed, the `aws eks get-token` command is run for generating a token. The token also has an expiration time after which no further requests can be made using it.  :
```
kind: Config
preferences: {}
users:
- name: <context>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - <region>
      - eks
      - get-token
      - --cluster-name
      - <cluster-name>
      command: aws
``` 

When the client libraries can't find the `aws` CLI in PATH, the requests fail and Meshery is unable to connect with the cluster. The error below is actually from Meshery server:
```
time="2021-09-14T10:42:58Z" level=error msg="failed to get K8s Config: Get \"https://<cluster-url>.eks.amazonaws.com/version?timeout=32s\": getting credentials: exec: exec: \"aws\": executable file not found in $PATH"
```

#### Implementation
* **Immediate solution**: Ship `aws` cli in Meshery's docker image so that the client libraries can handle authentication.
* **Possibly better solution**: Use [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) internally. (I'm not entirely sure about this yet)
