### ISSUE TITLE
[mesheryctl] panic on `system start` on Docker Desktop v4.1.0

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4344]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
There seems to be an incompatibility with `docker-compose`.

```
➜  ~ mesheryctl system start
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/meshery/meshery/mesheryctl/internal/cli/root/system.start(0x0, 0x0)
	/Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/system/start.go:177 +0x431c
github.com/meshery/meshery/mesheryctl/internal/cli/root/system.glob..func28(0x3913e20, 0x3af4978, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/system/start.go:88 +0x26
github.com/spf13/cobra.(*Command).execute(0x3913e20, 0x3af4978, 0x0, 0x0, 0x3913e20, 0x3af4978)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x390d520, 0x2c245e0, 0x3af4978, 0x0)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/meshery/meshery/mesheryctl/internal/cli/root.Execute()
	/Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/root.go:68 +0x56
main.main()
	/Users/runner/work/meshery/meshery/mesheryctl/cmd/mesheryctl/main.go:22 +0x25
```

#### Screenshots/Logs
<img width="872" alt="Screen Shot 2021-10-06 at 7 33 05 PM" src="https://user-images.githubusercontent.com/7570704/136302143-e3d37f9b-3c15-4906-957f-743d39d042f2.png">

**meshconfig**
```
➜  ~ cat .meshery/config.yaml
contexts:
  docker:
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-traefik-mesh
    - meshery-nginx-sm
    channel: stable
    endpoint: http://localhost:9081
    platform: docker
    token: Default
    version: latest
  k8s:
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-traefik-mesh
    - meshery-nginx-sm
    channel: stable
    endpoint: http://localhost:9081
    platform: k8s
    token: Default
    version: latest
  k8s-stable:
    endpoint: http://localhost:32627
    token: Default
    platform: kubernetes
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-traefik-mesh
    - meshery-nginx-sm
    channel: stable
    version: latest
  local:
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-traefik-mesh
    - meshery-nginx-sm
    channel: stable
    endpoint: http://localhost:9081
    platform: docker
    token: Default2
    version: latest
current-context: docker
tokens:
- location: auth.json
  name: Default
- location: /Users/lee/.meshery/auth.json
  name: Default2
```

#### Environment

- Host OS: Mac Intel
- Meshery Server Version: stable-v0.5.64-rc-2
- Meshery Client Version: stable-v0.5.64-rc-2
- Platform: Docker

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.meshery.io) and [Community Slack](http://slack.meshery.io)
