### ISSUE TITLE
Add middleware to support servicemesh names for SMP File Test Configuration

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#4482]
@piyushsingariya We should be using the service mesh's name right? That would be the better option here.

```
test:
  smp_version: v0.0.1
  id: d3ac6bf7-e35e-40c0-8669-5e13c9657286
  name: perf file test 2
  labels: {}
  clients:
    - internal: false
      load_generator: fortio
      protocol: 1
      connections: 2
      rps: 10
      headers: {}
      cookies: {}
      body: ''
      content_type: ''
      endpoint_urls:
        - 'https://github.com'
        - 'https://google.com'
  duration: 5s
mesh:
  type: 3
```

_Originally posted by @navendu-pottekkat in https://github.com/meshery/meshery/issues/4167#issuecomment-941990045_
