### ISSUE TITLE
[Lifecycle] Greedy deployment of Meshery Adapter for App Mesh 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4835]
#### Current Behavior
Deployment logic for the Meshery Adapter for App Mesh seems to be a bit off. When I deploy a Meshery system using this meshconfig:
```
meshery@mac64 ~ % cat ~/.meshery/config.yaml
contexts:
  local:
    endpoint: http://localhost:9081
    token: Default
    platform: kubernetes
    adapters: []
    channel: stable
    version: latest
current-context: local
tokens:
- location: auth.json
  name: Default
```

Meshery Server, Operator (broker and MeshSync) are deployed, but so, too, is an App Mesh adapter. See output from kubectl get pods:

```
NAMESPACE      NAME                                      READY   STATUS              RESTARTS       AGE
meshery        meshery-97565c89f-xrtdg                   0/1     ContainerCreating   0              42s
meshery        meshery-app-mesh-d8bb6fb98-4zrfj          1/1     Running             0              42s
meshery        meshery-operator-586c6f895d-wpkh9         0/2     ContainerCreating   0              42s
```

#### Expected Behavior
The Meshery Adapter for App Mesh should not be deployed.

#### Environment

- **Host OS:** Mac
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.6.0-rc-2
- **Meshery Client Version:** stable-v0.6.0-rc-2

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
