### ISSUE TITLE
[mesheryctl] New `meshconfig` format support to add `meshery-perf`

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#4893]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Desired Behavior

Three proposals have been considered since the inception of including `meshery-perf` in meshconfig. This issue is opened to confirm the proposals and implement the same.
**Proposal 1** focuses on adding meshery-perf as an add-on in meshconfig
```contexts:
  local:
    endpoint: http://localhost:9081
    token: Default
    platform: kubernetes
    adapters:
    - meshery-app-mesh
    - meshery-linkerd
    addons:
    - meshery-perf
    channel: stable
    version: latest
current-context: local
tokens:
- location: auth.json
  name: Default
```

**Proposal 2** focuses on adding load-generators as a separate array
```
contexts:
  local:
    endpoint: http://localhost:9081
    token: Default
    platform: kubernetes
    adapters:
    - meshery-app-mesh
    - meshery-linkerd
    load-generators:
    - meshery-nighthawk
    - meshery-fortio
    channel: stable
    version: latest
current-context: local
tokens:
- location: auth.json
  name: Default
```
**Proposal 3** replaces `adapters` with `components` and includes `meshery-perf` in the same array.
```
contexts:
  local:
    endpoint: http://localhost:9081
    token: Default
    platform: kubernetes
    components:
    - meshery-app-mesh
    - meshery-linkerd
    - meshery-perf
    channel: stable
    version: latest
current-context: local
tokens:
- location: auth.json
  name: Default

```

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
