### ISSUE TITLE
[mesheryctl] Token location is hardcoded.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#5570]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

```
contexts:
  local:
    endpoint: http://localhost:9081
    token: Default
    platform: kubernetes
    components: []
    channel: stable
    version: latest
current-context: local
tokens:
- location: ~/Downloads/test-2.json
  name: Default
```

`failed to write the token to the filesystem: open /Users/shabana/.meshery/~/Downloads/test-2.json: no such file or directory`
#### Desired Behavior

Token should be generated at path provided in config.
#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
