### ISSUE TITLE
Cytoscape-to-design conversion process tempering with the user-data

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#7921]
#### Current Behavior

When the two components with same name come together, in-order to differentiate them a random string is appended in key so that `design.services` has all unique keys. Unfortunately, the modification in key is also followed with the modification in the name of that component which is a human facing value, and has been provided via the same.

example-cyptoscape:
```
[
    {
        "data": {
            "id": "75ecb3ce-eda1-4d08-9af4-7126324f18d9"
        },
        "position": {
            "x": -1.8889034895672587,
            "y": -443.8490138133213
        },
        "scratch": {
            "_data": {
                "name": "application",
                "settings": {},
                "traits": {
                    "meshmap": {
                        "position": {
                            "posX": -1.8889034895672587,
                            "posY": -443.8490138133213
                        },
                        "label": "application",
                        "id": "75ecb3ce-eda1-4d08-9af4-7126324f18d9",
                        "edges": []
                    }
                },
                "version": "v1.25.2",
                "type": "Namespace",
                "apiVersion": "v1",
                "model": "kubernetes"
            }
        }
    },
    {
        "data": {
            "id": "880f7160-766f-4e1e-a7ea-cf1c87ff2193"
        },
        "position": {
            "x": -1.8889034895672596,
            "y": -452.8490138133213
        },
        "scratch": {
            "_data": {
                "name": "application",
                "namespace": "application",
                "settings": {},
                "traits": {
                    "meshmap": {
                        "position": {
                            "posX": -1.8889034895672596,
                            "posY": -452.8490138133213
                        },
                        "label": "application",
                        "id": "880f7160-766f-4e1e-a7ea-cf1c87ff2193",
                        "parent": "75ecb3ce-eda1-4d08-9af4-7126324f18d9",
                        "edges": []
                    }
                },
                "version": "4.5.1",
                "type": "Application",
                "apiVersion": "argoproj.io/v1alpha1",
                "model": "argo-cd"
            }
        }
    }
]
```

in the above example both the component have same name

The result received in the form of design-file-format:
```yaml
"name: Unitled Design
services:
  application-gutnr:
    name: application-gutnr
    type: Application
    apiVersion: argoproj.io/v1alpha1
    namespace: application
    version: 4.5.1
    model: argo-cd
    dependsOn:
    - application-igbjx
    traits:
      meshmap:
        edges: []
        id: 880f7160-766f-4e1e-a7ea-cf1c87ff2193
        label: application
        parent: 75ecb3ce-eda1-4d08-9af4-7126324f18d9
        position:
          posX: -1.8889034895672596
          posY: -452.8490138133213
  application-igbjx:
    name: application-igbjx <-- namespace value changed 🤸‍♂️ 
    type: Namespace
    apiVersion: v1
    version: v1.25.2
    model: kubernetes
    traits:
      meshmap:
        edges: []
        id: 75ecb3ce-eda1-4d08-9af4-7126324f18d9
        label: application
        position:
          posX: -1.8889034895672587
          posY: -443.8490138133213
"
```

Here the value of namespace was `application`, but after conversion it has been changed to `application-igbjx` which modifies the requirements of the user, **unknowingly**.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
