### ISSUE TITLE
[mesheryctl] system context create command doesn't add all the specified components

### ISSUE THREAD

**Issue by zakisk** [meshery/meshery#9162]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

I've added new context name `newContext` with below command
`mesheryctl system context create newContext --components meshery-istio meshery-nsm meshery-linkerd`
but only first adapter is added, see `.meshery/config.yaml` file
```
contexts:
    docker:
        endpoint: http://localhost:9081
        token: default
        platform: docker
        components:
            - meshery-cilium
            - meshery-linkerd
        channel: stable
        version: latest
        provider: Meshery
    local:
        endpoint: http://localhost:32489
        token: default
        platform: docker
        channel: stable
        version: latest
        provider: Meshery
    newContext:
        endpoint: http://localhost:9081
        token: default
        platform: kubernetes
        components:
            - meshery-istio
        channel: stable
        version: latest
        provider: Meshery
current-context: docker
tokens:
    - name: default
      location: auth.json
```
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
