### ISSUE TITLE
[Docs] Tutorial: Exploring Kubernetes Deployments with Meshery Playground

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#9869]
_This child issue is related to "[Playground] Learning Paths: Cloud Native tutorials with Meshery Playground #9832". See this issue for more context._

### Current State

Meshery Docs are in need of new tutorials with hands-on labs. In this tutorial, we will explore how to use Meshery Playground, an interactive live cluster environment, to perform hands-on labs for managing Kubernetes deployments. Meshery is a powerful tool that simplifies the adoption and operation of cloud and cloud native technologies. Meshery Playground provides a safe and isolated environment for learning and experimenting with these technologies.

### Desired State

1. Take the following sample and refactor in context of Meshery Playground. 
1. Instead of `kubectl` commands use Meshery UI and MeshMap as the primary mechanisms for users to perform tasks in the labs. Put CLI commands inside of `<details><summary></summary></details>` as an alternative reference.
1. Reference existing Meshery Designs from the Meshery Catalog both as starting point and/or as a finished example of the lab.
1. As needed, take screenshots or video recordings to enrich the content.

```yaml
---
layout: default
title: Exploring Kubernetes Deployments with Meshery Playground
abstract: Learn Kubernetes Deployments with Meshery Playground
permalink: guides/tutorials/kubernetes-deployments
redirect_from: guides/tutorials/kubernetes-deployments/
type: guide
category: tutorial
language: en
abstract: "In this tutorial, we will explore Kubernetes Deployments using Meshery Playground, an interactive live cluster environment, to perform hands-on labs for deploying and managing applications."
---

Introduction:
In this tutorial, we will delve into the world of Kubernetes Deployments, a key resource for managing and scaling containerized applications. Utilizing Meshery Playground, an interactive live cluster environment, we'll conduct hands-on labs to gain practical experience in deploying and managing applications using Kubernetes Deployments.

Prerequisites:
- Basic understanding of Kubernetes concepts.
- Meshery Playground access. If you don't have an account, sign up at [Meshery Playground](https://meshery.layer5.io/play).

Lab Scenario: Deploying and Scaling a Microservices Application

Objective:
Learn how to use Kubernetes Deployments to deploy and scale a microservices-based application.

### Steps:

#### 1. **Accessing Meshery Playground:**
   - Log in to the [Meshery Playground](https://meshery.layer5.io/play) using your credentials.
   - Navigate to the Meshery Playground dashboard.

#### 2. **Deploying a Microservices Application:**
   - Deploy a sample microservices application with multiple components using Kubernetes Deployments.

\```bash
# Deploying a sample microservices application
mesheryctl pattern apply -f https://raw.githubusercontent.com/example/microservices-app-deployment.yaml
\```

#### 3. **Scaling Deployments:**
   - Explore how to scale individual components of the microservices application by adjusting the replicas in the Deployment configuration.

\```bash
kubectl scale deployment <deployment-name> --replicas=3
\```

#### 4. **Updating Deployments:**
   - Learn how to update the microservices application by rolling out changes to the Deployment.

\```bash
kubectl set image deployment/<deployment-name> <container-name>=new-image:tag
\```

#### 5. **Rollback Deployments:**
   - Understand the process of rolling back changes in case of issues or errors during an update.

\```bash
kubectl rollout undo deployment/<deployment-name>
\```

#### 6. **Monitoring and Troubleshooting Deployments:**
   - Utilize Meshery Playground to monitor the status of Deployments and troubleshoot common issues.

#### 7. **Clean-Up:**
   - Delete the Deployments and associated resources after completing the lab.

\```bash
mesheryctl pattern delete -f https://raw.githubusercontent.com/example/microservices-app-deployment.yaml
\```

#### 8. **Saving and Sharing:**
   - Save your scenario in Meshery Playground for future reference.
   - Share your Deployment scenarios with the Meshery community for collaborative learning.

### Conclusion
Congratulations! You've successfully completed the lab on exploring Kubernetes Deployments using Meshery Playground. This hands-on experience has equipped you with practical knowledge on deploying, scaling, updating, and monitoring applications in a Kubernetes environment. Continue exploring more scenarios in the Meshery Playground to enhance your skills in container orchestration.

{% include related-content.html type="tutorials" %}


```

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
