### ISSUE TITLE
 [Docs] Tutorial: Understanding Kubernetes ConfigMaps and Secrets with Meshery Playground

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#9925]
_This child issue is related to "[Playground] Learning Paths: Cloud Native tutorials with Meshery Playground #9832". See this issue for more context._

### Current State

Meshery Docs are in need of new tutorials with hands-on labs. In this tutorial, we will explore how to use Meshery Playground, an interactive live cluster environment, to perform hands-on labs for managing Kubernetes deployments. Meshery is a powerful tool that simplifies the adoption and operation of cloud and cloud native technologies. Meshery Playground provides a safe and isolated environment for learning and experimenting with these technologies.

### Desired State

1. Take the following sample and refactor in context of Meshery Playground. 
1. Instead of `kubectl` commands use Meshery UI and MeshMap as the primary mechanisms for users to perform tasks in the labs. Put CLI commands inside of `<details><summary></summary></details>` as an alternative reference.
1. Reference existing Meshery Designs from the Meshery Catalog both as starting point and/or as a finished example of the lab.
1. As needed, take screenshots or video recordings to enrich the content.

```yaml
---
layout: default
title: Understanding Kubernetes ConfigMaps and Secrets with Meshery Playground
abstract: Learn how to work with ConfigMaps and Secrets in Kubernetes using Meshery Playground
permalink: guides/tutorials/kubernetes-configmaps-secrets
redirect_from: guides/tutorials/kubernetes-configmaps-secrets/
type: guide
model: kubernetes
kind: configmaps
category: tutorial
language: en
abstract: "In this tutorial, we will explore how to effectively use Kubernetes ConfigMaps and Secrets for managing configuration data and sensitive information. Leveraging Meshery Playground, an interactive live cluster environment, we'll perform hands-on labs to understand the practical aspects of working with ConfigMaps and Secrets in Kubernetes."
---

Introduction:
In this tutorial, we will delve into the realm of Kubernetes ConfigMaps and Secrets. ConfigMaps are used to manage configuration data, while Secrets handle sensitive information. Using Meshery Playground, an interactive live cluster environment, we'll perform hands-on labs to gain practical insights into working with ConfigMaps and Secrets in Kubernetes.

Prerequisites:
- Basic understanding of Kubernetes concepts.
- Meshery Playground access. If you don't have an account, sign up at [Meshery Playground](https://meshery.layer5.io/play).

Lab Scenario: Managing Application Configuration with ConfigMaps and Secrets

Objective:
Learn how to create and manage ConfigMaps and Secrets in Kubernetes to handle configuration data and sensitive information for your applications.

### Steps:

#### 1. **Accessing Meshery Playground:**
   - Log in to the [Meshery Playground](https://meshery.layer5.io/play) using your credentials.
   - Navigate to the Meshery Playground dashboard.

#### 2. **Creating a ConfigMap:**
   - Learn how to create a ConfigMap to store configuration data for your application.

\```yaml
# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  app.properties: |
    key1=value1
    key2=value2
\```

Apply the ConfigMap configuration:

\```bash
kubectl apply -f configmap.yaml
\```

#### 3. **Using ConfigMaps in Pods:**
   - Explore how to use ConfigMaps in your Pod specifications to inject configuration data into your application.

\```yaml
# pod-with-configmap.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx:latest
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: my-configmap
\```

Apply the Pod configuration:

\```bash
kubectl apply -f pod-with-configmap.yaml
\```

#### 4. **Creating a Secret:**
   - Learn how to create a Secret to store sensitive information, such as API keys or database credentials.

\```yaml
# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=  # Base64 encoded username
  password: cGFzc3dvcmQ=  # Base64 encoded password
\```

Apply the Secret configuration:

\```bash
kubectl apply -f secret.yaml
\```

#### 5. **Using Secrets in Pods:**
   - Explore how to use Secrets in your Pod specifications to securely pass sensitive information to your application.

\```yaml
# pod-with-secret.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret
spec:
  containers:
  - name: mycontainer-secret
    image: nginx:latest
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
\```

Apply the Pod configuration:

\```bash
kubectl apply -f pod-with-secret.yaml
\```

#### 6. **Updating ConfigMaps and Secrets:**
   - Learn how to update ConfigMaps and Secrets dynamically and observe the changes in the associated Pods.

\```bash
kubectl edit configmap my-configmap
kubectl edit secret my-secret
\```

#### 7. **Clean-Up:**
   - Delete the ConfigMap, Secret, and associated resources after completing the lab.

\```bash
kubectl delete configmap my-configmap
kubectl delete secret my-secret
kubectl delete pod mypod mypod-secret
\```

#### 8. **Saving and Sharing:**
   - Save your scenario in Meshery Playground for future reference.
   - Share your ConfigMap and Secret scenarios with the Meshery community for collaborative learning.

### Conclusion
Congratulations! You've successfully completed the lab on Understanding Kubernetes ConfigMaps and Secrets using Meshery Playground. This hands-on experience has equipped you with practical knowledge on managing configuration data and sensitive information in Kubernetes. Continue exploring more scenarios in the Meshery Playground to enhance your skills in cloud-native technologies.

{% include related-content.html type="tutorials" %}


```

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
